name: E_Library
description: This application is a digital library based application. You can borrow books here.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  badges: ^3.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  dio: ^4.0.6
  animations: ^2.0.7
  eva_icons_flutter: ^3.1.0
  google_fonts: ^4.0.3
  simple_animations: ^5.0.0+3
  lazy_load_scrollview: ^1.3.0
  file_picker: ^5.2.5
  intl: ^0.18.0
  custom_dropdown: ^0.0.2
  flutter_launcher_icons: ^0.12.0
  flutter_speed_dial: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/e-librray.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/profil/
